### PR TITLE
Manual - enable line wrapping in table cells

### PR DESCRIPTION
**Pull request by m-holger**

### CODE REVIEW

**Comment by jberkenbilt** [comment]
This is great, thanks! I'll update some of the other lists to be tables. In my perfect world, this is a pull request against `sphinx_rtd_theme`, I find out when a released version includes the patch, and then I remove the workaround. This is a little fragile since it depends upon class names in their html, but I'm willing to risk it for now since it has only a light dependency on something that is not very likely to change, at least not while maintaining the current bug.

If you tell me that you intend to submit a patch, great; otherwise, I'll take a look. Thanks again.

**Comment by jberkenbilt** [comment]
I have accepted this change manually into my work branch. Since it moved on since your PR, github didn't notice.

**Comment by jberkenbilt** [comment]
oops, didn't actually push to work yet. Let's see if github notices. If not, I'll close again.

**Comment by jberkenbilt** [comment]
didn't notice; closing manually.

**Comment by m-holger** [comment]
>  In my perfect world, this is a pull request against sphinx_rtd_theme, I find out when a released version includes the patch, and then I remove the workaround. 

There are various open issues (since 2014) and  PR's (since 2018) around this. I doesn't look to me like the default behavior of  sphinx_rtd_theme is going to change any time soon. At the same time, I don't think there is going to be any change that breaks this workaround which seems to be used by a number of projects.

**Comment by jberkenbilt** [comment]
Yes, that's why I accepted it. It's also small, self-contained, and low risk. The worst that happens is that my tables have horizontal scrollbars, in which case I or someone else will notice and point it out. I really appreciate your help on this one. There are several sections of the doc that read better with tables.

**Pull request closed without merging**
